scrape_configs:
  - job_name: "Client Service"
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: [ '192.168.1.123:9010' ]
      - labels:
          application: 'Client Service Microservice'

  - job_name: "User Service"
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: [ '192.168.1.123:9020' ]
      - labels:
          application: 'User Service Microservice'

  - job_name: "License Service"
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: [ '192.168.1.123:9030' ]
      - labels:
          application: 'License Service Microservice'

  - job_name: "CloudGateway Service"
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: [ '192.168.1.123:8080' ]
      - labels:
          application: 'CloudGateway Service Microservice'