services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: miguel
      MONGO_INITDB_ROOT_PASSWORD: miguel
      MONGO_INITDB_DATABASE: miguel
    ports:
      - 27017:27017
    networks:
      - miguel

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: miguel
      ME_CONFIG_MONGODB_ADMINPASSWORD: miguel
      ME_CONFIG_MONGODB_URL: mongodb://miguel:miguel@mongo:27017/
    networks:
      - miguel

networks:
  miguel:
    name: miguel-network